model_type: HMETS
project_info:
  basin_area_km2: 2340.0
  created_date: '2025-08-01T20:32:19.249583'
  description: HMETS model for Fraser River basin
  end_date: '2020-12-31'
  latitude: 50.1
  longitude: -122.8
  model_type: HMETS
  project_id: fraser_river_hmets
  project_name: Fraser River HMETS Model
  region: British Columbia
  start_date: '2010-01-01'
  status: planned
template_config:
  description: Semi-distributed model for snow-dominated watersheds
  model_type: HMETS
  optional_data:
  - humidity
  - wind_speed
  - radiation
  parameters:
    HMETS_RUNOFF_COEFF:
      default: 0.5
      max: 0.9
      min: 0.1
    SNOW_SWI:
      default: 0.05
      max: 0.1
      min: 0.01
  required_data:
  - precipitation
  - temperature_max
  - temperature_min
